### ISSUE TITLE
Eigen3 versions

### ISSUE THREAD

**Issue by pauljurczak** [libigl/libigl-example-project#26]
I noticed that installation of `libigl` includes source files of Eigen3 library. I already have Eigen3 installed in standard location `/usr`. Is `libigl` always going to find already installed version of Eigen3 with `FindEigen3.cmake` and use that version?

**Comment by jdumas** [comment]
Hi. So if you have a CMake target called `Eigen3::Eigen` that exists before you include/find libigl, then libigl's CMake will use this target and will not download a copy of Eigen. You should do that at your own risk though. The default behaviour if you do not provide a `Eigen3::Eigen` target yourself, is that libigl will download a copy of Eigen locally (in libigl's folder) and use it with your project.

**Comment by pauljurczak** [comment]
Hi Jeremie, thank you for responding. My current `CMakeLists.txt`:
```
cmake_minimum_required(VERSION 3.16.2)
project(subt VERSION 0.1.0 LANGUAGES CXX)

set(CPACK_PROJECT_NAME ${PROJECT_NAME})
set(CPACK_PROJECT_VERSION ${PROJECT_VERSION})
set(CMAKE_CXX_COMPILER /usr/bin/g++-8)
set(CMAKE_BUILD_PARALLEL_LEVEL 4)
include(CPack)

add_compile_options(-std=c++2a)

set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${CMAKE_CURRENT_SOURCE_DIR}/cmake)

option(LIBIGL_WITH_OPENGL            "Use OpenGL"         ON)
option(LIBIGL_WITH_OPENGL_GLFW       "Use GLFW"           ON)

find_package(LIBIGL REQUIRED QUIET)

find_package(catkin REQUIRED COMPONENTS
  roscpp
  std_msgs
  rosbag
  tf
  genmsg
  laser_geometry
  message_generation
  subt_ign
)

include_directories(
  /home/paul/subt_ws/install/include
  /home/paul/libraries/libigl/include
  /home/paul/libraries/libigl/external/glad/include
  /home/paul/libraries
  /opt/ros/melodic/include
  /usr/include/eigen3
  /usr/include/ignition/transport7
  /usr/include/ignition/msgs4
  /usr/include/ignition/math6  
  ${catkin_INCLUDE_DIRS}
)

add_executable(subt 
  main.cpp
  Scan2D.cpp
  Scan3D.cpp
  Image3D.cpp
  ElevationMap.cpp
  World.cpp
)

target_precompile_headers(subt PRIVATE common.h)

target_link_libraries(subt 
  ${catkin_LIBRARIES} 
  /opt/ros/melodic/lib/libactionlib.so 
  sfml-graphics 
  sfml-window 
  sfml-system
  # /usr/lib/x86_64-linux-gnu/libOpenGL.so
  # /usr/lib/x86_64-linux-gnu/libGLU.so
  igl::core 
  igl::opengl_glfw
)
```
So it looks like `libigl` should be using it's own copy of Eigen3, right? I don't explicitly include Eigen3 in this file, because it is being brought in as a ROS dependency in `find_package(catkin REQUIRED COMPONENTS`. 

When I print Eigen version from my executable, I get: `3.3.4` and that's the version installed in `/usr` directory. Also `CMakeCache.txt` for my project shows: `Eigen3_DIR /usr/lib/cmake/eigen3`, but it also shows: `LIBIGL_EIGEN_VERSION 3.2.10`.

**Comment by jdumas** [comment]
I think you might be trying to bite more than you can chew here. catkin seems like a large project and I have no idea how it works or how its find_package is importing the Eigen dependency. All I can tell you regarding libigl is: if you provide a target `Eigen3::Eigen` *before* calling `find_package(LIBIGL)`, then libigl will use it. Otherwise, it will define its own `Eigen3::Eigen` target based on a downloaded copy of Eigen. How this plays out with other libraries you are using in your project is your responsibility.

I encourage you to read tutorials about CMake best practices. CMake is a complex language and understanding how modern CMake should work takes time and effort. Here are some pointers I can suggest you to read carefully:
- [Effective Modern CMake](https://gist.github.com/mbinna/c61dbb39bca0e4fb7d1f73b0d66a4fd1#file-effective_modern_cmake-md) aggregates some useful pointers as well as a list of tips.
- [An Introduction to Modern CMake](https://cliutils.gitlab.io/modern-cmake/) is more of a guidebook on best practices not covered in CMake's documentation.
- [The CMake community wiki](https://gitlab.kitware.com/cmake/community/-/wikis/home) has up-to-date resources you can read to familiarize yourself with CMake.

**Comment by pauljurczak** [comment]
Thanks for your help. I realize the complexity of large CMake projects, I was just looking for some low hanging fruit. Perhaps it's wiser for me not to tinker with it for now.
